const fs = require('fs');
let rawdata = fs.readFileSync(process.argv[2]);  
let res = JSON.parse(rawdata);

console.log("\\documentclass[11pt]{article}")
console.log("\\usepackage[utf8]{inputenc}")
console.log("\\usepackage{graphicx}")
console.log("\\usepackage[margin=0.1in]{geometry}")
console.log("\\usepackage[dvipsnames]{xcolor}")
console.log("\\usepackage{yfonts}")
console.log("\\usepackage{aurical}")
console.log("\\usepackage[T1]{fontenc}")
console.log("\\usepackage{tabularx}")
console.log("\\usepackage{watermark}")
console.log("\\usepackage{tikz}")
console.log("\\newcommand*\\circled[1]{\\tikz[baseline=(char.base)]{")
console.log("\\node[shape=circle,draw,inner sep=2pt] (char) {#1};}}")
console.log("\\definecolor{OCRA}{RGB}{204,119,34}")
console.log("\\begin{document}")
console.log("\\thiswatermark{\\centering \\put(-50,-850){\\includegraphics[scale=1.5]{img/paper.jpg}} }")
console.log("\\begin{minipage}{0.5\\textwidth}")
console.log("\\includegraphics{img/zitto.png}")
console.log("\\end{minipage}%")
console.log("\\begin{minipage}{0.5\\textwidth}%\\raggedleft")
console.log("\\Huge{\\Fontauri " + res.CharacterName + " } \\\\")
console.log("\\Large{"+ res.CharacterClass.name +"} \\\\")
console.log("\\textcolor{OCRA}{" + "MasterMind" + "} \\\\")
console.log("NG")
console.log("\\vspace{1cm}")

console.log("\\begin{tabular}{cccccc}")
console.log("Str & Dex & Cos & Int & Wis & Cha \\\\ \\hline ")
console.log("8 & 18 & 13 & 8 & 10 & 20\\\\ ")
console.log(" & $\\bullet$ & & & & $\\bullet$")
console.log("\\end{tabular}")
console.log("\\vspace{1cm} \\\\")
console.log("\\textcolor{OCRA}{HP} \\circled{58} \\hspace{3cm} \\textcolor{OCRA}{AC} \\circled{15}")
console.log("\\end{minipage}")
console.log("\\vspace{0.5cm}")
console.log("\\begin{quote}")
console.log("\\textit{\\Fontauri \"Boblin is a rum gremlin, alienated from normal Gremlin society for trying to explain a philosophy about the greater good.\"}")
console.log("\\end{quote}")
console.log("\\begin{minipage}[t]{.5\\textwidth}")
console.log("{\\huge \\Fontauri Features}\\")
console.log("\\textcolor{OCRA}{Kenku}\\")
console.log("\\textbf{Mimica} Puoi riprodurre i suoni che hai sentito, incluse le voci.\\")
console.log("\\textbf{Contraffazione Esperta} Puoi duplicare manufatti e scritture di altre creature. Disponi di vantaggio \\")
console.log("\\textcolor{OCRA}{Bard}\\")
console.log("\\textbf{Bardic Inspiration}(d8)\\")
console.log("\\textbf{Jack of all trades} Half Proficiency to Ability Check\\")
console.log("\\textbf{Song of Rest} 1d6 to Short Rest\\")
console.log("\\textbf{Font of ispiration} BI regained with Short Rest\\")
console.log("\\textbf{Countercharm} As an action start to sing. All allies in 30f have adv on being charmed or frightened.\\")
console.log("\\textcolor{OCRA}{College of Lore}\\")
console.log("\\textbf{Cutting Words} When a creatures make an attack roll 60f from you you can use a BI and sub from the attack.\\")
console.log("\\textbf{Additional Magic Secrets}\\")
console.log("\\textcolor{OCRA}{Rouge}\\")
console.log("\\textbf{Cunning Action}\\")
console.log("\\textbf{Sneak Attack (1d6)}\\")
console.log("\\end{minipage}")
console.log("\\begin{minipage}[t]{.4\\textwidth}\\raggedleft")
console.log("\\begin{center}")
console.log("{\\Huge \\textgoth{P}} \\circled{\\Huge +4} \\hspace{0.3cm} {\\Huge \\textgoth{A}} \\circled{\\Huge+8} \\hspace{0.3cm} {\\Huge \\textgoth{S}} \\circled{\\Huge+9}")
console.log("\\end{center}")
console.log("\\vspace{0.5cm}")
console.log("{\Large \textbf{\\Fontauri Skills}}\\\\")
console.log("Athletics $\\bullet$\\\\")
console.log("Acrobatics \\ ")
console.log("Deception $\\bullet$\\\\ ")
console.log("Investigation \\\\")
console.log("Perception $\\bullet$ \\\\")
console.log("Performance $\\bullet$\\\\ ")
console.log("Stealth $\\bullet$ \\\\")
console.log("\\vspace{.5cm}")
console.log("{\\Large \\textbf{\\Fontauri Sailor Background}}\\\\")
console.log("A belaying pin(club)\\\\")
console.log("50 feet of silk rope\\\\")
console.log("A gemstone (coal for others)\\")
console.log("\\vspace{0.5cm}")
console.log("{\\Large \\textbf{ \\Fontauri Tools}}\\\\")
console.log("Navigator's tools\\\\")
console.log("vehicle(water)\\\\")
console.log("\\end{minipage}")
console.log("\\newpage")
console.log("\\thiswatermark{\\centering \\put(-50,-850){\\includegraphics[scale=1.5]{img/paper.jpg}} }")
console.log("\\begin{minipage}[t]{.5\\textwidth}")
console.log("{\\huge \\textbf{\\Fontauri Spells}}\\\\")
console.log("textcolor{OCRA}{Cantrips}\\\\")
console.log("Mending\\\\")
console.log("Message\\\\")
console.log("Vicious Mockery\\\\")
console.log("textcolor{OCRA}{1th Level (4)}\\\\")
console.log("Bane \\\\")
console.log("Charm Person\\\\")
console.log("Detect Magic\\\\")
console.log("Protection from Evil and Good\\\\")
console.log("\\textcolor{OCRA}{2nd Level (3)}\\\\")
console.log("Invisibility\\\\")
console.log("Shatter\\\\")
console.log("Enthrall\\\\")
console.log("Gift of Gab\\\\")
console.log("textcolor{OCRA}{3rd Level (3)}\\\\")
console.log("Fly\\\\")
console.log("Haste\\\\")
console.log("Fireball\\\\")
console.log("Hypnotic Pattern\\")
console.log("Stinking Cloud\\")
console.log("Wind Wall\\")
console.log("textcolor{OCRA}{4th Level (2)}\\")
console.log("Stone Shape\\")
console.log("Wall of Fire\\")
console.log("Hallucinatory Terrain\\")
console.log("Animate Objects")
console.log("\\end{minipage}")
console.log("\\%CONTINUE OF EQUIPMENT")
console.log("\\begin{minipage}[t]{.4\\textwidth}\\raggedleft")
console.log("{\\Large \\textbf{ \\Fontauri Equipment}}\\\\")
console.log("Magic Gun \\\\")
console.log("Entertainers pack\\\\")
console.log("Cli Lyre\\ - Broom of flying - Cap of Waterbreathing\\\\")
console.log("Leather armor \\\\")
console.log("Dagger\\\\")
console.log("Thieves tools\\\\")
console.log("Slippers of spider climbing\\\\")
console.log("\\end{minipage}")
console.log("\\end{document}")
